// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwo_pupZZIwu7I4KIv44LyndEvF5O8VI',
    appId: '1:930937268439:web:3b825cf58629c9a44ba892',
    messagingSenderId: '930937268439',
    projectId: 'intellicode-37f4f',
    authDomain: 'intellicode-37f4f.firebaseapp.com',
    databaseURL: 'https://intellicode-37f4f-default-rtdb.firebaseio.com',
    storageBucket: 'intellicode-37f4f.appspot.com',
    measurementId: 'G-6911NPMJVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRytHmPT08f6q94re2rB4de8aKK0uObwA',
    appId: '1:930937268439:android:bfb41ee19ef371e04ba892',
    messagingSenderId: '930937268439',
    projectId: 'intellicode-37f4f',
    databaseURL: 'https://intellicode-37f4f-default-rtdb.firebaseio.com',
    storageBucket: 'intellicode-37f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANvz0b3TVtgCERnetuqu6TqvJoCervYDc',
    appId: '1:930937268439:ios:fc9dca98366379634ba892',
    messagingSenderId: '930937268439',
    projectId: 'intellicode-37f4f',
    databaseURL: 'https://intellicode-37f4f-default-rtdb.firebaseio.com',
    storageBucket: 'intellicode-37f4f.appspot.com',
    iosBundleId: 'com.example.intellicode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANvz0b3TVtgCERnetuqu6TqvJoCervYDc',
    appId: '1:930937268439:ios:fc9dca98366379634ba892',
    messagingSenderId: '930937268439',
    projectId: 'intellicode-37f4f',
    databaseURL: 'https://intellicode-37f4f-default-rtdb.firebaseio.com',
    storageBucket: 'intellicode-37f4f.appspot.com',
    iosBundleId: 'com.example.intellicode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTwo_pupZZIwu7I4KIv44LyndEvF5O8VI',
    appId: '1:930937268439:web:fcba3a4dcb1a2fda4ba892',
    messagingSenderId: '930937268439',
    projectId: 'intellicode-37f4f',
    authDomain: 'intellicode-37f4f.firebaseapp.com',
    databaseURL: 'https://intellicode-37f4f-default-rtdb.firebaseio.com',
    storageBucket: 'intellicode-37f4f.appspot.com',
    measurementId: 'G-QDC4R3MP3F',
  );

}